name: api CD

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    defaults:
          run:
            working-directory: ./api
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: "ap-southeast-1"
    
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install EB CLI using pip
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy
